### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by soruly** [soruly/whatanime.ga-telegram-bot#1]
I'll investigate this issue later today
error log from pm2

```
telegram-5 (err): SyntaxError: Unexpected token < in JSON at position 0
telegram-5 (err):     at Object.parse (native)
telegram-5 (err):     at Request._callback (/home/soruly/projects/whatanime.ga-telegram-bot/index.js:70:31)
telegram-5 (err):     at Request.self.callback (/home/soruly/projects/whatanime.ga-telegram-bot/node_modules/request/request.js:187:22)
telegram-5 (err):     at emitTwo (events.js:106:13)
telegram-5 (err):     at Request.emit (events.js:191:7)
telegram-5 (err):     at Request.<anonymous> (/home/soruly/projects/whatanime.ga-telegram-bot/node_modules/request/request.js:1044:10)
telegram-5 (err):     at emitOne (events.js:96:13)
telegram-5 (err):     at Request.emit (events.js:188:7)
telegram-5 (err):     at IncomingMessage.<anonymous> (/home/soruly/projects/whatanime.ga-telegram-bot/node_modules/request/request.js:965:12)
telegram-5 (err):     at emitNone (events.js:91:20)
telegram-5 (err):     at IncomingMessage.emit (events.js:185:7)
telegram-5 (err):     at endReadableNT (_stream_readable.js:975:12)
telegram-5 (err):     at _combinedTickCallback (internal/process/next_tick.js:74:11)
telegram-5 (err):     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by soruly** [comment]
The server has an nginx config `client_max_body_size 300k;`
This is an assumption from https://github.com/soruly/whatanime.ga/blob/master/index.js#L499
The body should not exceed 300KB if it's a 640x360 jpeg (80% quality). 
However the telegram bot is getting the largest image file as in https://github.com/soruly/whatanime.ga-telegram-bot/blob/master/index.js#L36
So the bot is making a post request exceeding the 300KB limit
‘‘‘
telegram-4 (out): <html>
telegram-4 (out): <head><title>413 Request Entity Too Large</title></head>
telegram-4 (out): <body bgcolor="white">
telegram-4 (out): <center><h1>413 Request Entity Too Large</h1></center>
telegram-4 (out): <hr><center>nginx</center>
telegram-4 (out): </body>
telegram-4 (out): </html>
```
Now I temporarily raise the limit to 1024k on server, and would update the bot to choose a better sized image soon.

**Comment by soruly** [comment]
Not showing this error anymore.
